import { RiBookletLine } from "react-icons/ri";
import { LuUsers } from "react-icons/lu";
import { TbReportAnalytics } from "react-icons/tb";
import { IoSettingsOutline } from "react-icons/io5";
import { IoDocumentTextOutline } from "react-icons/io5";
import { MdHome } from "react-icons/md";
import { BsUpload, BsDownload } from "react-icons/bs";

export const navigateMenus = [
  {
    label: "홈",
    parentKey: "",
    key: "home",
    link: "/home",
    index: 1,
    level: 1,
    icon: <MdHome />,
  },
  {
    label: "제품관리",
    parentKey: "home",
    key: "assetManager",
    link: "",
    index: 2,
    level: 1,
    icon: <RiBookletLine />,
  },
  {
    label: "구성원관리",
    parentKey: "home",
    key: "userManager",
    link: "",
    index: 3,
    level: 1,
    icon: <LuUsers />,
  },
  {
    label: "문서관리",
    parentKey: "home",
    key: "assetDocument",
    link: "",
    index: 3,
    level: 1,
    icon: <IoDocumentTextOutline />,
  },
  {
    label: "고객사관리",
    parentKey: "home",
    key: "clients",
    link: "",
    index: 8,
    level: 1,
    icon: <TbReportAnalytics />,
  },
  {
    label: "고객사리스트",
    parentKey: "clients",
    key: "sub51",
    link: "/7bbef8fb-ab26-4969-a633-0ad164fc63d2",
    index: 81,
    level: 2,
  },
  {
    label: "고객사정보",
    parentKey: "clients",
    key: "sub51",
    link: "/5994c397-ba14-4595-a142-6ed2e76bb822",
    index: 81,
    level: 0,
  },
  {
    label: "엑셀저장",
    parentKey: "clients",
    key: "sub52",
    link: "/53738752-4a62-4aa0-8909-de473cd5b2a8",
    index: 82,
    level: 2,
  },
  {
    label: "보고서",
    parentKey: "home",
    key: "assetReport",
    link: "",
    index: 4,
    level: 1,
    icon: <TbReportAnalytics />,
  },
  {
    label: "회사정보",
    parentKey: "home",
    key: "companyInfo",
    link: "/c91b9c9b-cc95-4605-be48-5a359a4e100a",
    index: 5,
    level: 1,
    icon: <IoSettingsOutline />,
  },
  {
    label: "제품대장",
    parentKey: "assetManager",
    key: "sub11",
    link: "/eff179b5-a575-4046-99f3-ca0dc465af3e",
    index: 21,
    level: 2,
  },

  {
    label: "엑셀저장",
    parentKey: "assetManager",
    key: "sub12",
    link: "/ed4599ce-5808-462c-b10f-3eee0df54dd1",
    index: 22,
    level: 2,
  },
  {
    label: "대표견적",
    parentKey: "assetManager",
    key: "child11",
    link: "/8e4314e1-ec72-47b5-84e2-114a5e7a697a",
    index: 210,
    level: 3,
  },
  {
    label: "대표견적",
    parentKey: "assetManager",
    key: "child12",
    link: "/337a93f8-ff79-4ce9-95a7-6b041bb418f6",
    index: 220,
    level: 3,
  },
  {
    label: "자산인쇄",
    parentKey: "assetManager",
    key: "child13",
    link: "/261c956d-a9ce-4e22-aec2-8d9398b7af9b",
    index: 230,
    level: 3,
  },
  {
    label: "자산배정",
    parentKey: "assetManager",
    key: "child14",
    link: "/bd02aaba-5a6e-4abd-a759-a0ba067d982d",
    index: 240,
    level: 3,
  },
  {
    label: "자산반납",
    parentKey: "assetManager",
    key: "child15",
    link: "/347b529a-8c62-4ffd-b4a1-8ccf4bbf470f",
    index: 250,
    level: 3,
  },
  {
    label: "구성원등록",
    parentKey: "userManager",
    key: "sub21",
    link: "/0f55998a-7b77-426d-880d-3c6fd7ef4654",
    index: 310,
    level: 2,
  },
  {
    label: "구성원대장",
    parentKey: "userManager",
    key: "sub22",
    link: "/a7e05d80-6fa2-452c-b3c7-f4177fad2534",
    index: 320,
    level: 2,
  },
  {
    label: "배정문서대장",
    parentKey: "assetDocument",
    key: "sub31",
    link: "",
    index: 410,
    level: 2,
  },
  {
    label: "반납문서대장",
    parentKey: "assetDocument",
    key: "sub32",
    link: "",
    index: 420,
    level: 2,
  },
];
